drivers/soc: Remove add_hwgenerator_randomness function
Fix this compile error: implicit declaration of function 'add_hwgenerator_randomness' [-Werror,-Wimplicit-function-declaration]

In the https://github.com/halibw/android_kernel_xiaomi_oxygen/commit/75cc37f461de9f8a80aa381ee882cf70822ee4a2 commit, the dependency header for this function was changed. We can simply delete, or replace the random.h header declaration.